#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-javadoc-plugin
Version  : 3.0.0.m1
Release  : 1
URL      : https://github.com/apache/maven-javadoc-plugin/archive/maven-javadoc-plugin-3.0.0-M1.tar.gz
Source0  : https://github.com/apache/maven-javadoc-plugin/archive/maven-javadoc-plugin-3.0.0-M1.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/3.0.0-M1/maven-javadoc-plugin-3.0.0-M1.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-javadoc-plugin/3.0.0-M1/maven-javadoc-plugin-3.0.0-M1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
